### ISSUE TITLE
"Delete previous" twice when select 2nd page lead to freeze of program !

### ISSUE THREAD

**Issue by Nokia808** [junrrein/pdfslicer#100]
Hi. It is nice to see you again.

I upgraded to new version 1.7

Accidentally I selected 2nd page then click on "Delete previous" & did not save. Then clicked "Delete previous" again (when nothing previous further). This lead to freeze program, so that I was enforced to use kill the window applet of my Cinnamon to kill your program. Then I tried to relaunch program again but it did not respond ! I tried again to relaunch program but again not respond ! At that stage I shut-down system but system took about 29 minutes to complete shut-down !

I was in near to injure my system by forced shut-down but fortunately I did not do it ....  

Please to avoid such case, make "delete previous" inactive if nothing further "previous" to be deleted (due to repeated "Delete previous" clicking ! And I thing it is also good to make "Delete next" inactive if there is no further "next" to be deleted (due to repeated "Delete next" clicking, in which case can create similar situation ....

Thank you !

**Comment by amivaleo** [comment]
This is weird. I can't reproduce this on Gnome: the "delete previous" is indeed inactive for me if the 1st page is selected.

I have the same app version.

**Comment by Nokia808** [comment]
@amivaleo 
Sorry I made mistake in my description & I will edit even title. Is is produced when select 2nd page (not 1st page) then click "Delete previous" then click "Delete previous" again before saving .... Sorry for that mistake !

**Comment by amivaleo** [comment]
Oh I see! Now I can reproduce the issue. And yes, it's a proper issue.

**Comment by junrrein** [comment]
@Nokia808 

Thanks a lot for the bug report.

I fixed this in master, and in a couple of days (more or less) I'll make a bugfix release. I'm sorry for any work you may have lost as a result of this.
