### ISSUE TITLE
UI: change "About" label to "About PDF Slicer"

### ISSUE THREAD

**Issue by amivaleo** [junrrein/pdfslicer#101]
Hi!

This issue is exactly the same as the one I've just opened for Geary: https://gitlab.gnome.org/GNOME/geary/issues/469

I'm basically suggesting to use the same "format" for that label among the applications. Most of gnome apps use "About App_Name" instead of only "About". Can you please do the same? :)

**Comment by Nokia808** [comment]
This give me idea of adding new option: "About PDF file" which should show meta data of opened PDF like:

- Author
- produced
- editor
- date of creation
- date of last modification
- encrypted/nonencrypted
- keywords
- ........ etc

This will be nice feature !

**Comment by amivaleo** [comment]
That is surely something important to have somewhere, but I'm not sure that is one of Slicer goals. I see Slicer more as a Editor that as a Reader, which is (in my opinion) the best suitable place for such feature.

Evince should definitely have this feature (and it does, indeed, although the GUI there is a bit old! D: )

**Comment by Nokia808** [comment]
@amivaleo 
Hi amivaleo ! You did not understood me & you have all right for that. Dear the case is that: currently QPDF has no ability to edit PDF meta-data but it is on the road of development & developer will add it in future. I request this from him ..... So, it will be preparation for such upcoming new QPDF feature.

**Comment by amivaleo** [comment]
I don't see what I didn't understand but... Well... 🤷‍♂️

QPDF is a thing, Slicer is another.

Slicer doesn't have to support every single feature in QPDF.

I didn't say anything about "editing the metadata". I talked about "showing the metadata". I believe that such feature (showing the metadata) should be dealt by Evince (and it does, indeed).

Just because you mentioned *editing*: I would like to have a complete different *new* app for "editing the metadata".


Let's see what Julian thinks about this. My point of view (which is that of a simple user) is that Slicer should not manager metadata, neither showing nor editing.

**Comment by Nokia808** [comment]
@amivaleo 
Why it is simple functionality ! But we talking about something not introduced ! I just explain why I suggested it ...... Let we delay discussion about it till it introduced ....

**Comment by amivaleo** [comment]
> Why it is simple functionality

It's not the point. :) I argue about the fact that Slicer is and should remain an app that let the user shuffled the pages in a pdf, merge several pdfs and maybe crop them. The metadatas are something different to me, thus they should be dealt by another app.

This is my opinion anyway. Let's wait for Julian to know his thought. 👍

**Comment by junrrein** [comment]
@amivaleo 

I don't see why not, and indeed Gnome apps are moving in this direction, so let's do it :+1:

**Comment by amivaleo** [comment]
I'm not sure if you refer to the issue in the first post about the "About" label or to the topic Nokia808 brought in. 🤔

**Comment by junrrein** [comment]
@Nokia808 

> This give me idea of adding new option: "About PDF file" which should show meta data of opened PDF (...)

This is irrelevant to the issue at hand, but I'll take the opportunity to answer anyway.

Evince already does this, and on my system (using Fedora 30) using Nautilus to view file properties also shows this metadata. I don't see the necessity of adding this in Slicer.

> (...) currently QPDF has no ability to edit PDF meta-data but it is on the road of development & developer will add it in future. I request this from him ..... So, it will be preparation for such upcoming new QPDF feature.

Slicer definitely won't be getting support for editing file metadata. It's outside of its scope.

**Comment by junrrein** [comment]
@amivaleo 

Sorry for the confusion. I answered you two in separate comments.

**Comment by junrrein** [comment]
Fixed in 4dedfd70ada301c26319fd24dcfe6af15f9d1d94.
