### ISSUE TITLE
provide appimage for download

### ISSUE THREAD

**Issue by Lvaskz** [junrrein/pdfslicer#103]
Hi ,can you provide appimage for download?
see 
https://appimage.org/
https://github.com/AppImage/AppImageKit/wiki

**Comment by junrrein** [comment]
As stated in the [AppImage documentation](https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages), creating an AppImage requires extra work for each distribution an application wants to target. This is a non-starter.

I have already been burned by AppImages for big apps which didn't work on my non-niche distro (Fedora).

In contrast, both Flatpak and Snap are universal formats. Of course, they imply that each distro have to integrate these systems for them to work. But then it's work that I don't have to do.

Sorry if it sounds harsh. Have a nice day!
