### ISSUE TITLE
Rotated pages in source files get rendered with wrong rotation

### ISSUE THREAD

**Issue by amivaleo** [junrrein/pdfslicer#106]
Hi!

there must be something special about this pdf [plotm.pdf](https://github.com/junrrein/pdfslicer/files/3314477/plotm.pdf) because Slicer automatically crops and resizes it to fit a A4 format.

It doesn't happen with this other pdf [Senzanome.pdf](https://github.com/junrrein/pdfslicer/files/3314481/Senzanome.pdf) although it's not in A4 format.

More infos:
- the "bad" pdf was converted by a ps file (pdf2ps plotm.ps).
- the "good" pdf was produced using gimp.

Metadatas or whatever are different between the two, but I expect Slicer to simply load the page as I see it in Evince (or any other pdf reader).

Is it possible to do something about this? 🤔

**Comment by junrrein** [comment]
Hi there!

It seems it's not about Slicer automatically cropping and resizing the page, but about incorrectly detecting the page rotation.
Moreover, this only happens on the rendering side. When saving pages to a file, they are saved correctly.

I have a pretty good idea of the source of this bug.

Thanks for the report!
