### ISSUE TITLE
Labels for page removal operations are unclear

### ISSUE THREAD

**Issue by Nokia808** [junrrein/pdfslicer#107]
Hi. I tested version 1.7.1

I noticed that when I selected page 6, then click "Delete previous" then it will delete all pages before page 6 (from page 1 to 5).

And if I selected page 6, then clicked on "Delete next" then it will delete all pages after 6 (page 7 to last page of PDF).

Is this normal or a bug ?

If it is normal & intended, then I suggest to change name of action from "Delete previous" to "Delete all previous" & change name from "Delete next" to "Delete all next". Such a way avoid confusion !

**Comment by junrrein** [comment]
Hi there!

The behaviour is normal, but I agree that the labels are unclear.

There used to be a separate button in the toolbar for each of these actions, and at the time is was necessary to keep labels short. Now that the actions live in a menu, there is no need for this.

Thanks for the report!

**Comment by junrrein** [comment]
Fixed in e48f71871b7c4dc71ad40228c1299f9a4abbf905.
