### ISSUE TITLE
Added pdf thumbnails have a different zoom level

### ISSUE THREAD

**Issue by amivaleo** [junrrein/pdfslicer#109]
Hi!

Try this:

- open a pdf in slicer
- change the zoom level (higher or lower, it doesn't matter, but it is *crucial* that it doesn't remain the same default zoom level)
- add a pdf

=> the newly added pages have the default zoom level.

I'd expect them to have the same zoom level as those of the already open file.

Extra note: changing the zoom restores the correct size for all thumbnails

**Comment by junrrein** [comment]
Hi there, nice catch!

This also happens when restoring deleted pages. It turns out Slicer changed the size of existing thumbnails, but didn't remember the change for new ones.

Thanks for the report!
