### ISSUE TITLE
Updated italian translation

### ISSUE THREAD

**Issue by amivaleo** [junrrein/pdfslicer#111]
Sorry... I'm too lazy to fork the repo > updated the file > request a merge, for a single file. 😛

[it.zip](https://github.com/junrrein/pdfslicer/files/3326635/it.zip)

**Comment by junrrein** [comment]
This is a problem I created myself, but did you know that Slicer can get translated online [using Weblate](https://hosted.weblate.org/projects/pdf-slicer/)?

If you didn't, it's not your fault: the only indications I'm giving that people can do so is a badge at the top of the README file, and a link in the Flathub app page.

I know that I should add a section to the README specifically about "Contributing", where this fact is presented clearly, but I got lazy. You were a victim of my laziness, in a way.

I will merge the file you provided, so don't worry about it. I'm telling you this so it gets easier in the future.

Thank you!

**Comment by amivaleo** [comment]
Uh! That's much better!

Nope, I didn't know, so I did the "old" way as I did some time ago: editing the po file.

Now I do, so I'll use that from now on. Thank you for that, I wish it were a much more common choice. I get quite tired when I have to deal with "Damned Lies": they use the "old way".

**Comment by junrrein** [comment]
There are "extra" strings like the `.desktop` file description and AppData descriptions where their translations get managed in a separate file (`po/extra/extra.pot`). It shows up as the "Extra" component in the Weblate paged I linked to earlier. So if you want to translate those strings, that's where you can go.

**Comment by junrrein** [comment]
Merged in 94709df08c241471dd5236c74550f54d2a981d8e.
