### ISSUE TITLE
Merge all "Add a Document" actions into a single one

### ISSUE THREAD

**Issue by junrrein** [junrrein/pdfslicer#116]
Currently there three different "Add a Document" actions depending on where the user wants the added pages to be inserted.

This would be better served by having only one action, and having the insertion position be an option inside the "Open File" dialog.

**Comment by junrrein** [comment]
@amivaleo 

This how the "Add Document" dialog's preliminary implementation looks:

![Captura de pantalla de 2019-06-27 19-55-19](https://user-images.githubusercontent.com/962049/60306270-ed883380-9915-11e9-9504-fe4f6d85733c.png)

I have some specific doubts about this design, namely:

* Can the strings in (1), (2) and (3) be improved in any way?
* In (3): How should the "Insertion position" label be positioned/aligned?

Of course, any other suggestions are welcome.

**Comment by amivaleo** [comment]
I should look at what pdfmod does for the labels. 

As for now:

Maybe 2 can be "Add".

1... "Select document to add"?

I had to think about this. Now it's quite late here (2am) so I can't focus.

Can you change the radiobuttons to a combobox?

I suggest to set "End" as default selection: pdfmod only added at the end. Moreover: the very idea to "add" is to "put some more stuff to what you have already, without moving it". It's quite likely that the users might not notice such setting for a while.

**Comment by junrrein** [comment]
@amivaleo 

I agree about the suggestions to improve the labels. Did you have other ideas since then?

> Can you change the radiobuttons to a combobox?

I could, but there is a problem: A combobox can't contain an insensitive entry. So when adding a document "After the selected page" isn't an available action, that item wouldn't show up in the combobox, which I think is bad for discoverability.

> I suggest to set "End" as default selection: pdfmod only added at the end. Moreover: the very idea to "add" is to "put some more stuff to what you have already, without moving it". It's quite likely that the users might not notice such setting for a while.

I agree, nice suggestion.

**Comment by amivaleo** [comment]
> Did you have other ideas since then?

Not really. Apologies.

> A combobox can't contain an insensitive entry [...] which [...] is bad for discoverability.

Yeah... :| I don't really like that the bottom section in such dialog becomes taller. I can't see alternatives either.

If the radiobuttons are the only solution (and it looks like that's the case), what about putting them on a new line? The area becomes even taller, but I prefer to sacrifice that than to have "insert position" vertical-aligned in the middle. 🙈

**Comment by junrrein** [comment]
> Not really. Apologies.

No problem!

> Yeah... :| I don't really like that the bottom section in such dialog becomes taller.

I definitely share the sentiment.

> If the radiobuttons are the only solution (and it looks like that's the case), what about putting them on a new line? The area becomes even taller, but I prefer to sacrifice that than to have "insert position" vertical-aligned in the middle. :see_no_evil:

I agree that having the label on a new line is better than the current situation. Another alternative is having the label stay at the place it currently is, but top-aligned. Which would do you prefer? (Or which would be the lesser evil? :man_shrugging:)

**Comment by amivaleo** [comment]
> having the label stay at the place it currently is, but top-aligned

gnome-tweaks does something like that in the "fonts" (or "characters"?) tab. I don't like it, but it looks like something accepted in gnome.

...

Maybe it is a better solution, according to some rationale that I can't understand, but I have the feel that it exists. o.o

**Comment by junrrein** [comment]
@amivaleo 

Oh I didn't know gnome-tweaks did it like that. I think I'm going with that then.

I also wished there was a better way. Maybe we'll come up with it in the future. I heard that design is about iteration anyway :)

**Comment by junrrein** [comment]
Implemented as of e96082934d21e330d63c942fa62e20a8ea7b6068.

**Comment by junrrein** [comment]
@amivaleo 

Unfortunately, I discovered that I cannot use custom widgets inside a file chooser in a Flatpaked application :(

You didn't notice it (because version 1.7.3 and 1.7.4 weren't published to Flatpak yet) and I didn't notice it because I wasn't testing the Flatpak version (my fault). The custom widget gets silently ignored, and the selected file gets added at the end of the document.

I'll have to unfortunately revert this change.

**Comment by junrrein** [comment]
This is documented at https://developer.gnome.org/gtkmm/stable/classGtk_1_1FileChooserNative.html, section "Portal details". This also applies to Gtk::FileChooserDialog (though it's not documented).

**Comment by amivaleo** [comment]
:/

I guess it's ok to keep it as it is now: popover menu after clicking on the + button.

But, hey! Publish some new version of you have it, instead of keeping it only for you! 😎

**Comment by junrrein** [comment]
@amivaleo 

I would have published newer Flatpak versions if I could, but I'm hitting a bug in the Flathub build machinery. I'm pretty sure I've shared the report with you before.

**Comment by amivaleo** [comment]
> I've shared the report with you before.

Yes. But I misunderstood. I thought it was something that had got fixed before you wrote that.
