### ISSUE TITLE
Disable "Select odd pages" and "Select even pages" actions in corner cases

### ISSUE THREAD

**Issue by junrrein** [junrrein/pdfslicer#117]
Both actions should be disabled if the document has no pages.

The "Select even pages" action should be disabled if there is only one page.

Having them enabled all the time doesn't provoke any issues, so this has low priority.

**Comment by junrrein** [comment]
@miltolstoy 

> Under ActionBar::ActionBar() I changed this line
>
>     selectMenu->append(_("Select odd pages"), "win.select-odd");
>
> To these:
>
>     m_buttonSelectOddPages = Gio::MenuItem::create(_("Select odd pages"), "win.select-odd");
>     selectMenu->append_item(m_buttonSelectOddPages);
>
> Where `m_buttonSelectOddPages` is:
>
>     Glib::RefPtr<Gio::MenuItem> m_buttonSelectOddPages;
> I hoped that this will allow me to change visibility state of `m_buttonSelectOddPages`, but unfortunately I didn't found such API in documentation.
>
> Maybe I'm doing something wrong initially?

The basic problem is that this is the wrong approach to disable an action.

In most cases, you don't want to make the button dissappear when an action isn't available. It should still be displayed in the UI, but insensitive (greyed out). This signals the user that the action exists but can't be used right now because of some condition.

Besides, if the action has an associated keyboard shortcut (which is not the case for this issue, but I'm commenting in general), hiding the button still allows the user to perform the action using the shortcut, which could cause a bug depending on the action we are talking about.

The correct approach in this case would be to disable the corresponding `Gio::SimpleAction`s when the conditions are met. All of the actions are handled by the AppWindow, and you can disable/enable them when the quantity of pages change in the (badly named) `onSelectedPagesChanged` method.

**Comment by miltolstoy** [comment]
My initial question was exactly about button "insensitivity", I was not clear enough.
I found set_sensitive() call on Gtk::MenuButton and I'm wondering why I cannot do the same thing with Gio::MenuItem. Should I use some another class from Gtk namespace for these buttons instead of Gio::MenuItem?
Anyway I will take a look on Gio::SimpleAction.

**Comment by junrrein** [comment]
@miltolstoy Sorry, it was me who wasn't clear enough.

When you create a `Gio::MenuItem` associating it with an Action, as done [here](https://github.com/junrrein/pdfslicer/blob/3392426ea856c7643fa5f71f3e144aa7cf3360b7/src/application/actionbar.cpp#L76), whether the button will be sensitive or not is tied to whether the associated action is enabled or not.

So what you need to do is enable or disable the corresponding actions in [`AppWindow::onSelectedPagesChanged`](https://github.com/junrrein/pdfslicer/blob/3392426ea856c7643fa5f71f3e144aa7cf3360b7/src/application/appwindow.cpp#L595). When that happens, the `MenuItem` will be made sensitive or insensitive automatically. I hope this explanation helps.

**Comment by miltolstoy** [comment]
@junrrein 
Thanks again. It became clear now.
Please assign this issue to me.
