### ISSUE TITLE
Change "Open" to "Add" after the first pdf is loaded

### ISSUE THREAD

**Issue by amivaleo** [junrrein/pdfslicer#119]
Hi!

I was thinking: what if the "Open" button is replaced by an "Add" button (which would work as the current + button) after the first pdf is loaded?

I think that the "Open" button is quite useless after the first pdf is loaded.

What do you think about this?

**Comment by junrrein** [comment]
In my mind, the Open button serves also as a means to start a new editing session: "I'm done with the current document. Let's start with another one".

This would make more sense after (or if ever) #83 gets implemented.

On the other hand, where we to remove the Open button after using it, I wonder it it makes sense having it in the first place? In this case, having only and Add File button would be enough.

**Comment by amivaleo** [comment]
>  Open button serves also as a means to start a new editing session

Uh! You're right.

Uhm... Just to consider other possibilities:

1. open pdfslicer with no file > *only* the open-button is shown
2. open a file in that session > the open-button is removed and it is replaced by the add-button
IF the user wants another pdfslicer > put a "new window" label-button in the hamburger menu all the time.

In some sense, this behaviour mimics what gedit does. Gedit doesn't have a "add file" feature, but it open files in different tabs (which is something that you will NEVER do, right!? Please... o.o), and still it has a "new window" feature.

What do you think?

> having only and Add File button

I do not agree: "add" means "there's already something open, and you want to load something more". "open" means "there's nothing open, so load something in the first place". I can't think at any software having and "add" button instead of a "open" button when nothing is loaded.

**Comment by junrrein** [comment]
> Uhm... Just to consider other possibilities:
> 
> 1. open pdfslicer with no file > _only_ the open-button is shown
>
> 2. open a file in that session > the open-button is removed and it is replaced by the add-button
>        IF the user wants another pdfslicer > put a "new window" label-button in the hamburger menu all the time.

Having a "New Window" button in the hamburger menu is something that should be there anyway, so thanks for the suggestion. I'm tracking that at #124.

I'm getting warmed up to your proposal. I can see how it makes sense, but I'm not convinced yet.

> In some sense, this behaviour mimics what gedit does. Gedit doesn't have a "add file" feature, but it open files in different tabs (which is something that you will NEVER do, right!? Please... o.o), and still it has a "new window" feature.
> 
> What do you think?

If Slicer ever gets support for tabs (which I'm not discounting) then Slicer would still need both the Open and Add buttons right? One for opening a file in a new tab, and the other to add a file to the current tab.

Still, I think having tabs should be delayed until the app gets support for drag-and-drop of pages, since it would be a natural action to try when having multiple tabs.

> > having only and Add File button
> 
> I do not agree: "add" means "there's already something open, and you want to load something more". "open" means "there's nothing open, so load something in the first place". I can't think at any software having and "add" button instead of a "open" button when nothing is loaded.

PDF Shuffler has something kinda like this. It only has a single "Import Pdf" button. It probably isn't the best example to take design ideas from lol, but that's where I got the idea.

**Comment by amivaleo** [comment]
> I'm getting warmed up to your proposal. I can see how it makes sense, but I'm not convinced yet.

I gotta find some other argument to win this. 😄

> If Slicer ever gets support for tabs (which I'm not discounting) then Slicer would still need both the Open and Add buttons right? One for opening a file in a new tab, and the other to add a file to the current tab.

Uhm! I didn't think about that scenario in which having tabs make sense indeed. And yes, it should have both buttons. By now, I can't really see every detail in the gui for when it will support tabs.

> PDF Shuffler has something kinda like this. It only has a single "Import Pdf" button. It probably isn't the best example to take design ideas from lol, but that's where I got the idea.

That's a solution. I don't like that because I think "import", to me, means something like "try to open a file which you usually can't read" or "open a file from a very remote position like a webservice or a remote machine". PDF Mod doesn't have such "import" file, it uses two separate buttons for those features, just like pdfslicer now.

**Comment by junrrein** [comment]
> > PDF Shuffler has something kinda like this. It only has a single "Import Pdf" button. It probably isn't the best example to take design ideas from lol, but that's where I got the idea.
> 
> That's a solution. I don't like that because I think "import", to me, means something like "try to open a file which you usually can't read" or "open a file from a very remote position like a webservice or a remote machine". PDF Mod doesn't have such "import" file, it uses two separate buttons for those features, just like pdfslicer now.

I agree, the term "import" usually has the meaning you are talking about.

I'm sorry, but I'm ultimately not convinced to change these buttons for now. I commend you for your dedication though! Thanks for all of your suggestions.

**Comment by amivaleo** [comment]
> I'm sorry, but I'm ultimately not convinced to change these buttons for now.

No problem! As long as the usage of your app is not slowed down and the gui looks nice&easy-to-use, I'm fine. :)

> I commend you for your dedication though! Thanks for all of your suggestions.

It's truly a pleasure to talk with you. Even if sometimes you are stick to your position, I really appreciate the fact that you don't behave like a bully! 😂
