### ISSUE TITLE
Add ability to combine multiple PDF files into single PDF at one process

### ISSUE THREAD

**Issue by Nokia808** [junrrein/pdfslicer#120]
Hi. You recently added ability to add PDF at begin, at end, after selected page options. This is okay if I like to combine 2 PDF files one after other.

But in many occasions I need to combine multiple PDF files, like 15 chapters each from separated PDF book or - & this is more common case - 15 PDF each represented scientific article about same topic like CA brain, into single PDF file for personal use. In this case I have to repeat process 15 times ! But if PDF Slicer has ability to combine multiple PDF files into single PDF at single process, then it will be very useful .......

It is common need for many users not occasional - specially for those working in scientific field .....

**Comment by junrrein** [comment]
If all of the files to add exist in the same directory, then this function could be satisfied by having the ability to select multiple files in the "Add File" dialog. This functionality should be present anyway, but it didn't cross my mind, so thanks for the idea!

In the other hand, if you want to combine files from different directories, I don't think I want to accommodate that use case.

**Comment by fikrillah** [comment]
i'm waiting for this, drag and drop multiple files would be nice...

**Comment by junrrein** [comment]
This is implemented as of ae1666873df310a26e899f81018646d67698e9b6, and it will be included in the next release.
