### ISSUE TITLE
Add a "New window" button to the hamburguer menu

### ISSUE THREAD

**Issue by junrrein** [junrrein/pdfslicer#124]

**Comment by amivaleo** [comment]
Since it is strictly related to this, please remember to add **ctrl+N** shortcut to trigger the very same action as this "New window" button!

**Comment by junrrein** [comment]
@amivaleo 

Definitely, thanks for the reminder.

**Comment by junrrein** [comment]
This action could also have a corresponding entry in the app launcher's context menu (like gnome-terminal has entries for "New window" and "Preferences").

**Comment by amivaleo** [comment]
Yes! I was also thinking at this when I wrote https://github.com/junrrein/pdfslicer/issues/127#issuecomment-536423919

**Comment by junrrein** [comment]
This is completely implemented as of 58f1c9a7ad0ba34e9022f910c1b1173986e2fc44. Happy holidays!

**Comment by amivaleo** [comment]
> This is completely implemented as of [58f1c9a](https://github.com/junrrein/pdfslicer/commit/58f1c9a7ad0ba34e9022f910c1b1173986e2fc44). Happy holidays!

Have a nice holiday too, Julian 💪
