### ISSUE TITLE
Missing ctrl+0 shortcut 

### ISSUE THREAD

**Issue by amivaleo** [junrrein/pdfslicer#126]
Hi!

Can you please add the shortcut **ctrl + 0** (it's a zero) to set the zoom to the default value?

This is like one of the standard shortcuts according to the HIG: https://developer.gnome.org/hig/stable/keyboard-input.html.en

:)

**Comment by junrrein** [comment]
Nice suggestion, thanks!

**Comment by amivaleo** [comment]
Uhm... Actually there are other shortcuts missing.

I'll open other issues for them. Don't get mad for that! :D

**Comment by junrrein** [comment]
No problem! Have at it!
