### ISSUE TITLE
Missing ctrl+Q shortcut

### ISSUE THREAD

**Issue by amivaleo** [junrrein/pdfslicer#128]
Hi!

Can you please add **ctrl+Q** shorcut following the HIG https://developer.gnome.org/hig/stable/keyboard-input.html.en ?

It should close the main window, no matter if it has some open file or not. Of course, a dialog should ask the user if he wants to save any unsaved change.

**Comment by junrrein** [comment]
Hey there, it's been a while.

This is a nice suggestion, thanks!

**Comment by amivaleo** [comment]
> Hey there, it's been a while.

Yep. It's nice to see that, even after months, you always re-appear!
