### ISSUE TITLE
Allow bigger zoom levels

### ISSUE THREAD

**Issue by nacho-domatix** [junrrein/pdfslicer#129]
Would be great to be able to zoom using Ctrl+Wheel mouse. Also I don't see why there's a limitation in the zoom (why not make it closer?)

**Comment by junrrein** [comment]
Hi there!

The part about using Ctrl + Mouse wheel to zoom is already tracked at #52.

A limitation in the zoom is there because, well, I guess there's got to be a limit :man_shrugging:

Is adding one bigger zoom level good enough?

**Comment by dxnacho** [comment]
A limit must be set, but I don't see any reason it should be less than Evince's one (which is around 383,9%). Not everyone has the same combination of screen resolution, size, eyesight....

**Comment by junrrein** [comment]
I do think the zoom limit in Slicer's main window should be less than Evince's, since Slicer has a "Big preview" button for each page that allows you to see a specific page in bigger zoom levels.

I can agree that it can be necessary to add more zoom levels for both views, but I think having Evince-levels of zoom in the main view is excessive.

**Comment by junrrein** [comment]
I just implemented this as of b137bd60afcfb00f2f7e6a72635cc8e736b7b00d.

I will notify you @nacho-domatix when I make a new release, so you can test this and we can tweak the zoom levels. Happy holidays!

**Comment by nacho-domatix** [comment]
Beautiful effort, thanks so much!!

Next for the "drag and drop" files one ;)

Happy holidays dude and thank you for all the work.

**Comment by junrrein** [comment]
@nacho-domatix 

Now that a new release has been made, could you tell me if the new zoom levels are enough?

As an added goodie, the zoom level is now remembered between Slicer runs.

**Comment by nacho-domatix** [comment]
I'll give you feedback you as soon as I get the new version in my distro (Manjaro). many thanks again!!

**Comment by junrrein** [comment]
Closing this issue since information wasn't provided.

The thing about zooming using Ctrl+Mouse wheel is being tracked at #52.
