### ISSUE TITLE
Information: Turkish translation of PDF Slicer is done.

### ISSUE THREAD

**Issue by libreajans** [junrrein/pdfslicer#132]
I want to thank all developers for the application. I have done the Turkish translation for PDF Slicer on Weblate.

https://hosted.weblate.org/languages/tr/pdf-slicer/#overview

**Comment by junrrein** [comment]
Hi there, thanks a lot for your contribution!

I've been inactive on Slicer lately, but the next release will contain your Turkish translation.

Cheers!
