### ISSUE TITLE
Flatpak version doesn't use the custom theme

### ISSUE THREAD

**Issue by amivaleo** [junrrein/pdfslicer#135]
Hi,

I remember that flatpaks used to not follow the custom theme set by the user.

I personally like Adwaita and I would only use that, IF several other things were fixed...

By the way, Slicer still doesn't use the custom theme.

**Comment by junrrein** [comment]
Hi there,

Flatpak definitely supports using custom themes, *if* they are also published at Flathub.

Here is the Flatpak-ed Slicer using the Arc theme:

![Captura de pantalla de 2019-10-03 11-51-38](https://user-images.githubusercontent.com/962049/66138062-68777f00-e5d4-11e9-8cd0-8b77eb0c4b37.png)

For me, this simply worked by using `flatpak update` when using a custom theme. Flatpak detects your current theme, and tries to install the Flatpak-ed theme automatically if it is available.

To install the Flatpak-ed theme manually, see [this](https://www.linuxuprising.com/2018/05/how-to-get-flatpak-apps-to-use-correct.html).

**Comment by amivaleo** [comment]
> themes, _if_ they are

That "if", indeed, doesn't hold in my case.

Still I don't fully understand this.

I have other flatpacks, like Builder, Fragments, Fractals, Glade and so on. They all use my theme, no matter which one that is, whether it's published in flathubs or not. PDF Slicer doesn't.

Why is that?

**Comment by junrrein** [comment]
I didn't have any of those apps from the list installed. I tried Fragments, and in my system it works the same way as Slicer: it only uses custom themes if they were also installed from Flatpak.

To me it seems that you used some kind of trick [like this](https://forums.linuxmint.com/viewtopic.php?t=284418) to make your custom themes available to the Flatpak runtime. Is this your case?  
What's different between Slicer and the apps you listed is that Slicer is still using the Gnome 3.32 runtime, while those others are already on the 3.34 version. So if you applied that trick to the 3.34 runtime, it wouldn't work for Slicer.

Anyway, Slicer isn't doing anything special, and I don't think those apps are doing anything special either.

**Comment by amivaleo** [comment]
> Is this your case?

Nope...

I tell you what I did: I extracted the css stylesheets from adwaita and I edited them so to separate the dark variant from the light variant. Then I wrote a script with the help of another guy, that automatically checks the time and switches from one theme (say: the light variant) to the other (the dark variant) at sunsets and sunrises.

That's all I did.

And PDF Slicer is the only flatlpak application that is not affected by that, i.e. it doesn't switches theme accordingly.

I use the flatpak version also of Gimp, gnome-todo, gnome-note, and so on. 🤷‍♂️

**Comment by junrrein** [comment]
I can keep guessing at what's unique to your system that those applications can use arbitrary custom themes, but those would only be guesses after all. :man_shrugging:

Another guess that I have is that [once Slicer updates its runtime to 3.34](https://github.com/flathub/com.github.junrrein.PDFSlicer/pull/23) it will behave just like those other apps in your system. Fingers crossed.

AFAIK there is nothing I can do on my end.

**Comment by amivaleo** [comment]
Indeed,

```
$ flatpak info com.github.junrrein.PDFSlicer | grep Runtime
Runtime: org.gnome.Platform/x86_64/3.32
```
I checked several flatpaks I have, and it seems that pdfslicer is the only one that uses 3.32.

**Comment by amivaleo** [comment]
After the latest updated yesterday, I can see that slicer now uses 3.34. Maybe this is why it also follows the system theme, even if it is not listed in flathub (as for my case).

**Comment by junrrein** [comment]
Nice to see it worked, even if we don't know why lol
