### ISSUE TITLE
Please update flatpak package on FlatHub to last version !

### ISSUE THREAD

**Issue by Nokia808** [junrrein/pdfslicer#142]
Hi dear. Please update flatpak package on FlatHub to last version. The available package on FlatHub is version 1.7.2 while you reached till now to version 1.7.4

**Comment by junrrein** [comment]
Hey there. I can't publish new releases to Flathub for now because of a bug in the Flatpak build machinery: https://github.com/flathub/flathub/issues/1078.

Cheers
