### ISSUE TITLE
In the single-page view, move the zoom buttons to the window title

### ISSUE THREAD

**Issue by junrrein** [junrrein/pdfslicer#146]
From https://github.com/junrrein/pdfslicer/issues/86#issuecomment-514519115 (@amivaleo):

>(...) I suggest to remove the overlay zoom-buttons and replace them with a set a buttons like in eog.
>
>![](https://user-images.githubusercontent.com/24316547/61774593-769c6880-adf7-11e9-8a35-84da753e9d70.png)
>
>The only extra I'd like to suggest is to use a slider in the popover menu that appears if you click on the number in the middle.

**Comment by junrrein** [comment]
For the initial implementation, it would be enough to just create a Headerbar for the PreviewWindow and then move the zoom buttons there.

I still haven't defined a percentage zoom and what it would mean. I should take a look at Evince's code for that.

**Comment by miltolstoy** [comment]
Hi.
Please assign this one to me.
