### ISSUE TITLE
Remove ellipsis from "Open..." button on the headerbar

### ISSUE THREAD

**Issue by amivaleo** [junrrein/pdfslicer#150]
Hi!

I believe that the "Open..." button on the headerbar shouldn't have the ellipsis "...".

I found only one example for that in Glade. Unfortunately, I can't find anything about this in the HIGs. Yet, I suggest to remove them. Honestly I've never seen ellipsis in any button on the headerbar. Maybe the same should be done for the "Save As..." button. 🤔️

**Comment by junrrein** [comment]
Hey, thanks for the report!

The guideline I've used is that, if a button spawns a dialog window, then its text should have ellipsis at the end to signal that "more is coming".

But what you are saying is valid: those are pretty much not used for headerbar buttons across other applications. So I agree that they aren't necessary, and they are going away.

**Comment by amivaleo** [comment]
Yup. I know about that rule, but it looks like it doesn't apply for buttons on the headerbar. o.O
At least, I've never seen any ellipsis on the headerbar anywhere.
