### ISSUE TITLE
Untraslated strings - po files need to be rebased...?

### ISSUE THREAD

**Issue by amivaleo** [junrrein/pdfslicer#151]
Hi!

I've noticed a few unlocalized strings in the gui. Like "New Window" in the main menu, and "After selected pages" in the "+" button on the headerbar.

I checked the po file for my language (italian) and I couldn't find those strings.
Can you please check this issue? Maype the po files need to be rebased.

**Comment by junrrein** [comment]
Hey there!

That's strange. I can definitely find those strings in the po file for the Italian language. Maybe you have an older checkout?

"New window": https://github.com/junrrein/pdfslicer/blob/9c5a0c35a865ea77244f30749f0701a948e11105/po/it.po#L109

"After the selected page": https://github.com/junrrein/pdfslicer/blob/9c5a0c35a865ea77244f30749f0701a948e11105/po/it.po#L158

What's strange, is that the second one appears to be translated already?

Anyway, I suggest that you translate strings for Slicer using Weblate: https://hosted.weblate.org/projects/pdf-slicer/translations/it/

**Comment by amivaleo** [comment]
:|
I always forget about that website.

I see they're not translated that. I'm working on them now.

**Comment by amivaleo** [comment]
Done. :)

**Comment by junrrein** [comment]
Thanks for the contributions! :)
