### ISSUE TITLE
Add ability to invert the current selection

### ISSUE THREAD

**Issue by rugk** [junrrein/pdfslicer#167]
Use case:
1. I select all pages I want to have extracted.
2. I see around afterwards in the UI and notice I should have done it the other way around. :facepalm: 
3. I am sad. :disappointed:

Let's not make kiddens sad…

![grafik](https://user-images.githubusercontent.com/11966684/80133551-aef6f000-859d-11ea-94ad-37c4e89dfc61.png)

Solution: 
**Have an invert selection** button.
So after step 2. I find it, can invert my selection, then delete all selected, and here we are… I can go on. :smiley:

**Comment by junrrein** [comment]
Hi there! Your can already do what you want by using the "Remove unselected pages" function.

Even then, having "Invert selection" functionality could be useful for other cases. Thanks for the suggestion!

**Comment by miltolstoy** [comment]
Hi.
I would like to work on this issue.
Please assign it to me.

**Comment by junrrein** [comment]
This is implemented as of 2fe88ae9aea71493a9da0d63a6b8070f76217fe6 and will be included in the next release.

Thanks a lot @miltolstoy!
