### ISSUE TITLE
Giving multiple file names should open in the same instance

### ISSUE THREAD

**Issue by Vanadiae** [junrrein/pdfslicer#169]
Currently, when opening multiples files with this application (like when selecting multiples PDF in nautilus and opening with this application), there is one instance by PDF file that is created.

The expected behavior is to add all the pages of those files to one instance.

Steps to reproduce:
- Select multiple files with nautilus and right click > "Open with application" > PdfSlicer or run this command `flatpak run com.github.junrrein.PDFSlicer <pdf_1> <pdf_2>`.
- there will be multiple instance that opens

**Comment by junrrein** [comment]
Hi there. I agree with your reasoning. That this didn't perform the expected result was probably an oversight.

Thanks for the report!

**Comment by miltolstoy** [comment]
Hi.
Please assign this issue to me, I'll handle it.
