### ISSUE TITLE
Use common selection pattern

### ISSUE THREAD

**Issue by Vanadiae** [junrrein/pdfslicer#171]
Currently, the selection is handled by clicking on each page, that is added to the selection and removed on a new click. This isn't quite consistent with other GTK apps that follow the GNOME HIG. It would be great if it followed [it](https://developer.gnome.org/hig/stable/selection-mode.html.en). 

I don't have C++ knowledge so I won't be able to help on this side.

**Comment by junrrein** [comment]
Hi there! This has come up before, and here's the [corresponding issue](https://github.com/junrrein/pdfslicer/issues/85) about it. You are welcome to add specific suggestions in there.

I'm closing this issue as a duplicate.
