### ISSUE TITLE
Suggestion about Improving name meaningfulness

### ISSUE THREAD

**Issue by Thejuampi** [junrrein/pdfslicer#18]
https://github.com/junrrein/pdfslicer/blob/9c06387211064983c8bd25941c77a069aa52e1c7/src/backend/documentsaver.cpp#L10

Taking into account the application works with just PDFs, I think it is a good idea to change the name to PdfSaver. (PDF = Portable **Document** Format)

I also suggest rename methods
`saveDocument()` and `writePdfFile()` 
to
`save()` and `persist()` (or `writeToDisk()`, but it think it is better just `persist()`) respectively

**Comment by junrrein** [comment]
> Taking into account the application works with just PDFs, I think it is a good idea to change the name to PdfSaver. (PDF = Portable Document Format)

But then shouldn't the Document class be renamed to Pdf, for consistency?

I implemented the other suggestions, thanks!

**Comment by Thejuampi** [comment]
> > Taking into account the application works with just PDFs, I think it is a good idea to change the name to PdfSaver. (PDF = Portable Document Format)
> 
> But then shouldn't the Document class also be renamed to Pdf, for consistency?
> 
> I implemented the other suggestions, thanks!

One step at a time

**Comment by junrrein** [comment]
Fixed by 2bd59099d66d8622950598ee1279c4f0013b7065
