### ISSUE TITLE
Show page numbers

### ISSUE THREAD

**Issue by kparal** [junrrein/pdfslicer#20]
I quite often need to remove specific pages from a PDF document, e.g. pages 37 and 85 should be removed. This is not easily possible with PdfSlicer, because it doesn't show page numbers (as opposed to e.g. PdfShuffler). So in order to remove the right pages, I have to know what they look like (which might be tricky, if many of them look similar from the thumbnail) and just wildly guess their relative position in the app window.

Please show page numbers alongside the thumbnail, thank you.

**Comment by junrrein** [comment]
This is a good idea, thanks! I'll definitely implement this.

**Comment by kparal** [comment]
I don't have any strong opinions, both options work. You have a lot of white space between the thumbnails, so I'd personally probably use some of that whitespace to show the page number (i.e. label under the thumbnail).

**Comment by junrrein** [comment]
@kparal Good point on there being unused whitespace. I'll probably go with that option.

**Comment by junrrein** [comment]
This is how it looks:

![](https://github.com/junrrein/pdfslicer/raw/master/docs/readme-screenshot-2.png)

**Comment by kparal** [comment]
Great! Will look forward to it in the next Flathub release.
