### ISSUE TITLE
Keyboard shortcut to move pages left or right

### ISSUE THREAD

**Issue by abhijeetviswa** [junrrein/pdfslicer#202]
There are no keyboard shortcuts to move pages left or right. Such a shortcut would be really useful when moving around pages quickly. I went ahead and [created a patch](https://github.com/abhijeetviswa/pdfslicer/commit/c33bfd78cd9f19c31dbc07298dd7e7d442496dd6) on my fork. If this change is acceptable, I'll create a PR. Just wanted to discuss things first.

**Comment by junrrein** [comment]
Hi there! First of all, sorry for taking so long to respond.

I totally agree with you, the shortcut would be useful, and the ones you chose look fine to me :+1: 

There's only a small typo, and I added a comment using the Github UI. I'll be happy to accept your PR.

**Comment by abhijeetviswa** [comment]
Thank you for your reply! I've made the necessary changes, rebased onto master, and created PR #211.
