### ISSUE TITLE
Migrate to up-to-date Gnome runtime

### ISSUE THREAD

**Issue by doczipeter** [junrrein/pdfslicer#224]
flatpak says:

```
Info: org.gnome.Platform//3.38 is end-of-life, with reason:
The GNOME 3.38 runtime is no longer supported as of August 19, 2021. Please ask your application developer to migrate to a supported platform.
Applications using this runtime:
com.github.junrrein.PDFSlicer
```

**Comment by needlesslygrim** [comment]
It look as if the developer hasn't been online in the last year so I don't think it will get updated

**Comment by doczipeter** [comment]
Weird, as flatpak history shows 3 updates to the app in the last 3 months. Someone is working on it.

**Comment by needlesslygrim** [comment]
Hm strange

**Comment by doczipeter** [comment]
The flatpak runtime has been pumped up to Gnome 41. Closing this issue.
