### ISSUE TITLE
Adwaita Dark Theme not working

### ISSUE THREAD

**Issue by baumkuchen42** [junrrein/pdfslicer#34]
The Adwaita Dark Theme is not recognised by PDFSlicer. Principally, it is possible to execute it manually with GTK_THEME=Adwaita:dark as environment variable to get it displayed in the dark design. But it's rather strange that the application doesn't adapt automatically, I never had this problem with other flatpak applications before. I'm running it on Arch Linux.

**Comment by junrrein** [comment]
This is working fine here on Fedora 29, and it also works fine with the Arc theme. I don't have enough reason to believe this is a problem with this app. If you find more info indicating otherwise, do let me know.
