### ISSUE TITLE
Web site title typo PFD/PDF

### ISSUE THREAD

**Issue by sknorr** [junrrein/pdfslicer#41]
There is a typo on the Website, seemingly coming from: https://github.com/junrrein/pdfslicer/blob/gh-pages/_config.yml#L2 : PFD -> PDF.

(Also I just discovered this tool -- thank you! It looks really good and it is fast as far as I can tell.)

**Comment by junrrein** [comment]
Hi there, and thanks for the report!

And you're welcome! I'm glad this little tool could be of use.
