### ISSUE TITLE
Save into the same directory as the original document

### ISSUE THREAD

**Issue by kparal** [junrrein/pdfslicer#48]
When I hit save, it always defaults to the home directory, and it doesn't even remember last selected directory during the session. It would be very convenient if the save dialog could show the same location as the source PDF was selected from, by default.

**Comment by junrrein** [comment]
Thanks for the report. I agree, it should have worked this way form the beginning.

**Comment by junrrein** [comment]
As mentioned in #72, doing this isn't possible when Slicer is running under Flatpak, since Flatpak doesn't let me know the real location of opened files. I'm reverting this change.
