### ISSUE TITLE
New app icon?

### ISSUE THREAD

**Issue by bertob** [junrrein/pdfslicer#51]
Since the new GNOME app icon guidelines are in effect now, I'm reaching out to ask if you'd be interested in a new icon following those guidelines. Here's an initial concept:

![image](https://user-images.githubusercontent.com/1908896/54631076-825bd500-4a7b-11e9-8bfb-fd6c0be35481.png)

**Comment by junrrein** [comment]
Hi @bertob, sorry for taking so long to respond.

The icon you designed looks great! I will be very glad to adopt it.

If you have no further considerations to make, you can send the icon to my email (junrrein at gmail dot com) along with the necessary information to give you credit for your work.

**Comment by bertob** [comment]
Ok, sent you an email :)

**Comment by junrrein** [comment]
The new icons have been merged at e55033fa259c618b7068e4ae023f90f5c33166a8. I've made a new release, and it will take a day till it makes it to Flathub.

Many thanks to you and Lapo!
