### ISSUE TITLE
Zoom with Ctrl+Scroll

### ISSUE THREAD

**Issue by rugk** [junrrein/pdfslicer#52]
Zooming with:
* buttons works
* <kbd>Ctrl</kbd>+<kbd>+</kbd>/<kbd>Ctrl</kbd>+<kbd>-</kbd> works

However, it does not work with just scrolling while holding Ctrl.

In Nautilus, this e.g. works.

**Comment by junrrein** [comment]
I don't see why not.

**Comment by junrrein** [comment]
This is implemented for both the main window and the page window as of d88df80f7e6d1145ea9489fd1424e011dcb132ed.
