### ISSUE TITLE
Crashes with a certain pdf

### ISSUE THREAD

**Issue by sojusnik** [junrrein/pdfslicer#53]
When selecting f.i. the first three pages of [this](https://mega.nz/#!ao4B3SSL!1nRf7x1wMpMRaIVNjN6S5mUy_E9YQ9EWEFphBYAv5Nk) pdf and then removing the others, then your app crashes when saving it.

Happens with the latest version from Flathub (1.5.3) on Ubuntu 18.10.

**Comment by junrrein** [comment]
Thanks for the report. I can reproduce this.

I'll see if I can test saving that file using a minimal program, to see whether it is a problem with Slicer or with the underlying library it uses.

**Comment by junrrein** [comment]
Disabling the code that copies PDF annotations makes this bug disappear.

**Comment by junrrein** [comment]
Fixed as of version 1.6.0.
