### ISSUE TITLE
Compression/file size when saving not optimal

### ISSUE THREAD

**Issue by rugk** [junrrein/pdfslicer#56]
## Example

The whole [UML PDF](https://www.omg.org/spec/UML/About-UML/#docs-normative-supporting) is around 20MB of size. When you convert it and split only a small part (~15 pages) out of it, the resulting file is possibly even _bigger_ than the original file!

## So?

I guess this is just some bad compression or so.
In any case, this should possibly not happen…

**Comment by junrrein** [comment]
Thanks for the report. I agree there is something wrong here.

I hit a similar bug when saving a PDF that was heavy on annotations. Maybe the root causes are the same.

**Comment by junrrein** [comment]
I have tested this a little and found out this bug is unrelated to annotations.

**Comment by junrrein** [comment]
Fixed as of version 1.6.0.
