### ISSUE TITLE
Allow selecting pages when they are still loading

### ISSUE THREAD

**Issue by rugk** [junrrein/pdfslicer#57]
When you open a document with a lot of pages (> 700) and scroll, you may have to wait some time for the PDF thumbnails to be generated.

During that time, however, you cannot select any items.

Actually you should be able to select the files already, as (use case:) there is a good chance you already have the file open in your PDF viewer and already know the pages you want to extract/manipulate.

**Comment by junrrein** [comment]
I think you hit this problem with the UML PDF you mentioned in your other report :)

I can see why this is a problem, and I agree, Slicer should allow you to do this.
