### ISSUE TITLE
[Feature request] Utilize QPDF as backend instead of PDF-Writer

### ISSUE THREAD

**Issue by Nokia808** [junrrein/pdfslicer#59]
Hi. There is a very very powerful command line program called QPDF. Unfortunately it has no GUI.
It will elevate your application up if you utilize it as a backend in addition to poppler. 

See it at:
https://github.com/qpdf/qpdf

It's developer very active & very co-operative. However, he is not interested in creation of a frontend to it's application. Inspite this fact he is very ready to help any one like to create a GUI for his program.

**Comment by junrrein** [comment]
Hi there. I understand what you are requesting, but there is a small confusion: QPDF would replace PDF-Writer, not Poppler, since the latter is used for rendering pages, not slicing documents.

It would be a nice idea to test this library and see if it works better than PDF-Writer, since the latter is the source of a couple of bugs currently.

**Comment by Nokia808** [comment]
@junrrein 
Thank you very much for replays !
I edited title of this issue to be correct.
Dear please consider this seriously. QPDF is very powerful tool with advanced options. You can create great PDF editor.
It's developer ready to assist any one like to create GUI for it.
Also, QPDF is of much less bugs ..... There is bug reports in it's GitHub. But to me I did not suffer from any one. 
However, it very inconvenient to deal with PDF using command line only .....

**Comment by sojusnik** [comment]
@junrrein You could also take a look on [pikepdf](https://github.com/pikepdf/pikepdf), a python library based on QPDF. Its [features](https://github.com/pikepdf/pikepdf#features) speak for themselves.

**Comment by junrrein** [comment]
As of version 1.6.0, Slicer uses QPDF instead of PDF-Writer.

Thanks a lot for the suggestion!

**Comment by Nokia808** [comment]
@junrrein 

Dear, you already disappoint me when you said that you will not build advanced PDF editor ! 
What is benefit from using QPDF if not to create advanced PDF editor ?!
By using QPDF you can build advanced PDF editor without loss too much time because it is little bit bugy.

If you want to thank me really, then please make ALL QPDF features & powers available by your application ......

Please read QPDF manual to see it's powers ......

**Comment by junrrein** [comment]
@Nokia808 

I offer PDF Slicer free of charge. If it doesn't satisfy your needs, you are welcome to look elsewhere. I hope you find what you are looking for.
