### ISSUE TITLE
[Feature request] Insert PDF within other PDF file

### ISSUE THREAD

**Issue by Nokia808** [junrrein/pdfslicer#63]
For example I have a PDF of 50 pages. I have other PDF composed from 1 page or 3 pages & I like to insert it within 1st PDF that was composed of 50 pages originally.

You should allow user to specify where like to insert 2nd PDF:
- at beginning (before 1st page of 1st PDF), or
- at end (after last page of 1st PDF), or
- within 1st PDF (like after page 40 of 1st PDF)

**Comment by junrrein** [comment]
I consider this to be effectively the same as merging multiple documents into one (#30).

Whether this is the kind of UI we want to go for or not is the matter of design. But again, this can be discussed in the other report.
