### ISSUE TITLE
Please look for this application if useful to your development efforts

### ISSUE THREAD

**Issue by Nokia808** [junrrein/pdfslicer#65]
Please look to this program that it's developer stop from completing it's development:

http://jpdftweak.sourceforge.net/
https://sourceforge.net/projects/jpdftweak/

It is very powerful tool but need to adding few features to make it a good replacement for many Adobe acrobat pro for Linuxers. In fact with Okular can do this. However, as I said, his developer stop from it's development. I contact him about this.

It contain most of features of PDF manipulation ! Just few push forward & will be excellent ! Unfortunately I'm not programmer ..... Any one continue it's development will make soo good for peoples ......

Please see it. May be useful for your application or you can take over to complete it's development under new name. It is open source application.

**Comment by junrrein** [comment]
I'm not interested in contributing to a Java project, sorry.

**Comment by junrrein** [comment]
I looked around in that project's source code, and it seems that the PDF library it uses is also a Java one, so I won't be able to make use of it.

**Comment by Nokia808** [comment]
Never-mind ! I understand you. 

Only one note: I'm afraid that java is needed to create powerful PDF editor on Linux since PDF-Studio (strongest commercial PDF editor available for Linux is java). I wish I'm wrong .......

**Comment by junrrein** [comment]
You can create a powerful PDF editor in any language, if you had the desire and resources to do so.

Just FYI, it is not my intention to create a powerful editor, but a simple one.
