### ISSUE TITLE
Remove unselected pages crash the application when all pages are selected

### ISSUE THREAD

**Issue by amivaleo** [junrrein/pdfslicer#66]
Hi!

Try this:

Open any PDF in Slicer > Select ALL pages > click on the hamburger-menu on the bottom bar.

"Remove unselected pages" should not be clickable, because there are no unselected pages.
If that "Remove unselected pages" is clicked, the application crashes.

:)

**Comment by junrrein** [comment]
Thanks for the report! That's a nice catch :)
