### ISSUE TITLE
UI change - avoid two hamburger-menus?

### ISSUE THREAD

**Issue by amivaleo** [junrrein/pdfslicer#67]
Hi!

I noticed that Splicer uses the same icon for two different menus: the hambuger-menu on the topleft of the headerbar and the hamburger-menu on the bottom bar.

I haven't found suggestion about this in the HIGs. Still, I'd like to suggest to avoid using the same icon twice (or more) on the same window, it makes the two buttons a bit misleading imho.

I would like to suggest a different approach for the couple of buttons trash+hamburger on the bottom bar, similar to that used in nautilus headerbar:
[ 🗑 | ⯆ ]

What do you think? :)

**Comment by junrrein** [comment]
Hi there, thanks for the report! I agree completely with this.

In the past, I wasn't able to find a standard icon that looked the same as the Nautilus one, though pointing up. But right now I found the `pan-up-symbolic` icon that seems exactly what we're looking for.

**Comment by junrrein** [comment]
I ended up going with the upwards-arrow for this icon, since the button is located at the bottom of the screen.
