### ISSUE TITLE
Select all button

### ISSUE THREAD

**Issue by amivaleo** [junrrein/pdfslicer#69]
Hi!

Can you please add a "select all" button somewhere? :)
There's an icon for that in the standard/default icon theme already.

**Comment by junrrein** [comment]
Hi there,

What would be the use-case? To rotate every page in the document?

**Comment by amivaleo** [comment]
Well yeah.
Right now it could be only that.

I was thinking a bit ahead about some "burst" option that will produce one pdf per page, from the selected pages.

**Comment by junrrein** [comment]
> Well yeah.
Right now it could be only that.

Then it doesn't make much sense to support this, but it wouldn't hurt either.

> I was thinking a bit ahead about some "burst" option that will produce one pdf per page, from the selected pages.

I will be upfront with you: I don't want to have those sorts of features in Slicer. The workflow I have in mind is "whatever you can see right now in the view area, that's what's going to be saved".

**Comment by junrrein** [comment]
Alternative looks:

* Icon button (edit-select-all-symbolic) with "Select all pages" tooltip

![Captura de pantalla de 2019-06-22 20-02-44](https://user-images.githubusercontent.com/962049/59969701-8b50bc80-952a-11e9-8c17-197d75177ec2.png)

* Text button

![Captura de pantalla de 2019-06-22 20-08-08](https://user-images.githubusercontent.com/962049/59969699-81c75480-952a-11e9-8b8f-cfa3fdd48c18.png)

Which do you think works better? We should keep in mind that we'll also have #78 later, that is, extra related buttons.

**Comment by amivaleo** [comment]
I think that the icon-based button is ok. I saw that icon somewhere else already. Anyway, it's made for that purpose (it's the "edit-select-all-symbolic" icon, or something like that) so it's ok to use it. Also, I don't know if you're planning to make a mobile version of Slicer: it it better to already use some narrow gui for that.

But I'd suggest a different order:

[Cancel Selection| "SelAll" ]

I suggest this because when the features in #78 are ready, I think it would be good to put them in a popover menu like the one for the trash-bin-button (with the very same order: icon-button | top-arrow-button):

[Cancel Selection| "SelAll" | ^ ]

**Comment by junrrein** [comment]
> Also, I don't know if you're planning to make a mobile version of Slicer: it it better to already use some narrow gui for that.

Let's cross that bridge when (and if) ever we get to it.

> But I'd suggest a different order:
> 
> [Cancel Selection| "SelAll" ]
> 
> I suggest this because when the features in #78 are ready, I think it would be good to put them in a popover menu like the one for the trash-bin-button (with the very same order: icon-button | top-arrow-button):
> 
> [Cancel Selection| "SelAll" | ^ ]

I thought about another option. When the features in #78 are ready, I think that the "Cancel Selection" should stay as a standalone button, and then have the linked [SelAll | SelOdd | SelEven] buttons before it. Logically I think that batch selection is a different kind of action than de-selection.

What do you think? I know I have a history of just doing whatever I want in the end, but I promise I'm keeping an open mind. :sweat_smile:

**Comment by amivaleo** [comment]
> Logically I think that batch selection is a different kind of action than de-selection.

You're right. Indeed I can agree on keep them separeted.

> have the linked [SelAll | SelOdd | SelEven] buttons before it.

This could be a solution, *but*...! Think at how large that triplet of buttons would be: only the "select all" has an image, the others would be label-based I suppose. They would take a lot of space.

> I have a history of just doing whatever I want

I truly believe the opposite. I'm still here, so it means you're prone to listen (at least!) and you're not sticked to your beliefs. I like helping you with your app because of that and also because I like how you're shaping it so to make it truly "gnomish".

*Please remember*: I don't care about gnome being gnome, I care about a coherent UI language among all the apps, for the sake of the users. And you're doing well.

**Comment by junrrein** [comment]
> This could be a solution, but...! Think at how large that triplet of buttons would be: only the "select all" has an image, the others would be label-based I suppose. They would take a lot of space.

I was hoping that I could find icons for the "select-odd" and "select-even" actions, but I can't find any results for those in Google. So we'll have to go with label-based buttons, and they would indeed take a lot of space.

If we can still agree on keeping selection and cancel-selection separated, another solution we can go with is having the following:

[Select All -- ▲]  [Cancel Selection]

Where the "Select All" button would be label-based, and the "up triangle" is a menu with the other two options. I recognize this is essentially the suggestion you gave, just having the "Cancel Selection" as a separate entity.

I'm not keen on using the "edit-select-all-symbolic" icon, because I believe it fails at communicating its meaning, at least compared with the other buttons in the interface.

> I truly believe the opposite. I'm still here, so it means you're prone to listen (at least!) and you're not sticked to your beliefs. I like helping you with your app because of that and also because I like how you're shaping it so to make it truly "gnomish".
>
> Please remember: I don't care about gnome being gnome, I care about a coherent UI language among all the apps, for the sake of the users. And you're doing well.

That is reassuring to hear. You're being tremendous help as well, so thanks for that!

**Comment by amivaleo** [comment]
> in Google

Please, no! 😱 Custom icons make a mess if the user sets a different theme. >.<

> "edit-select-all-symbolic" icon [...] fails at communicating its meaning

Indeed. I agree. It should look like the one in android ( ![PHtyiNxXneikN6u4fbWJ9l5+NN3od4VM7Ee9z66Xyl0RDeeL3kcnFt06Vl9l4u5q9q3fq+Tu8HvShuirSbQP224n6P0D4mJTdyX6XN8AAAAASUVORK5CYII=](https://user-images.githubusercontent.com/24316547/60114198-a2ceb600-9773-11e9-9da3-06b7555d57f5.png) ), since it is more probable that users might recognize it. Maybe it will be changed some day...

What about the "object-select-symbolic" showing a popover menu with "select all, select odd, select even"?

I think you're right about not linking that with the "cancel selection" button. So yes, do not link them. I guess it's not a good choice to link an action and its opposite. 🤔

I'm not sure about the order: [cancel selection] [select] or [select] [cancel selection]

Uhm... Dunno.

Honestly? I'd like to have one single button for select/unselect. Android does that, but it doesn't have any "odd/even" selection.

May I question this feature in #78 ? ^_^ I mean: just... When/why could that be useful? 🤔

**Comment by junrrein** [comment]
> Please, no! :scream: Custom icons make a mess if the user sets a different theme. >.<

I don't see why this would be the case. If an icon theme doesn't provide the icons, then the UI would fall back to the icons provided by the app.

> What about the "object-select-symbolic" showing a popover menu with "select all, select odd, select even"?

I think "object-select-symbolic" won't be better than "edit-select-all-symbolic", especially now that Slicer no longer draws a checkmark on selected pages.

> Honestly? I'd like to have one single button for select/unselect. Android does that (...)

A single button for select/unselect? Can you tell me of a specific example in Android? I would like to see it in action.

> May I question this feature in #78 ? ^_^ I mean: just... When/why could that be useful? :thinking:

I don't know when that could be useful, and I don't know why two months ago I said it could be lol. I'm now asking the guy in that issue for use-cases.

**Comment by amivaleo** [comment]
> If an icon theme doesn't provide the icons, then the UI would fall back to the icons provided by the app.

Icons in the default theme should be on custom themes too. If they don't, the authors of the custom theme have to be blamed.

Let us put in the case in which only the default theme is used (which I really hope for, but other things should change in order to make it an acceptable choice):

If you use an icon from elsewhere, I see a potential risk of using some icon that doesn't fit with the others of the (default) theme. It might not happen, but Julian... I'm watching you
![watching-you](https://user-images.githubusercontent.com/24316547/60124614-4c20a680-978a-11e9-9cfc-2352fee24c59.png)

> Can you tell me of a specific example in Android?

I have this "File Manager" app on my phone, made from the mother company (look at the top right corner): https://im.ezgif.com/tmp/ezgif-1-649766fbb8ac.gif

I guess other similar apps might do the same.

> I don't know why two months ago I said it could be lol

😄

**Comment by junrrein** [comment]
> If you use an icon from elsewhere, I see a potential risk of using some icon that doesn't fit with the others of the (default) theme. It might not happen, but Julian... I'm watching you

Haha it's good to know someone is looking after this apps quality! :laughing:

Being serious: I don't see why Slicer can't provide custom icons for actions, _as long as_ they fit with the rest of the Adwaita icon theme. Whether third-party icon themes would bother with providing customized versions of these icons is not Slicer's problem (as we both agree).

> I have this "File Manager" app on my phone, made from the mother company (look at the top right corner): https://im.ezgif.com/tmp/ezgif-1-649766fbb8ac.gif

I get an "The url you entered is invalid or has expired" image on that link.

**Comment by amivaleo** [comment]
> it's good to know someone is looking after this apps quality!

That's how it is! D:

^_^

> I don't see why Slicer can't provide custom icons

Only it they don't match exactly the same style as the default ones.


> as long as they fit

Exactly.

>  Whether third-party icon themes would bother with providing customized versions of these icons is not Slicer's problem (as we both agree).

Correct.

> I get an "The url you entered is invalid or has expired" image on that link.

I upload that here:
![a](https://user-images.githubusercontent.com/24316547/60129385-2351de80-9795-11e9-859c-35b693c945a9.gif)

**Comment by junrrein** [comment]
Thanks for the example.

In that UI, what do you do if you want to cancel the current selection? Hit the "back" button?

**Comment by junrrein** [comment]
By the way, the other person [provided use-cases for the "Select Odd" and "Select Even" actions](https://github.com/junrrein/pdfslicer/issues/78#issuecomment-505584486), and they are convincing enough for me. They'll get implemented.

**Comment by amivaleo** [comment]
Yes, the X button on the left. Or you tap the same button on the right twice.

This is basically the "selection mode" that gnome has too.

It can't be used in Slicer nor elsewhere without a proper well-designed pair of icons and a better gui for the selection-mode: it's arder to find the blue "cancel (selection)" button on a blue background. You can check that on gnome-boxes or gnome-books, for example.

So, let's back to Slicer:
- a couple of buttons (no clever ideas on the order they should follow)
- not linked

(*IF* no good icons can be found for select-odd/select-even)
- the select-button uses a label only
- that button opens a popover with two label-button: selOdd, selEven

(*IF* good icons can be found)
- ?

**Comment by junrrein** [comment]
> Yes, the X button on the left.

I didn't see that button before, thanks. What I wanted to gleam from this was if the app used separate select all/unselect all buttons, and I see it does.

> It can't be used in Slicer nor elsewhere without a proper well-designed pair of icons and a better gui for the selection-mode: it's arder to find the blue "cancel (selection)" button on a blue background. You can check that on gnome-boxes or gnome-books, for example.

Slicer is kind of different from those apps, in that the selection-mode is permanent, so the learned lessons in the design department are difficult to translate.

> So, let's back to Slicer:
> 
> * a couple of buttons (no clever ideas on the order they should follow)
> 
> * not linked
> 
> 
> (_IF_ no good icons can be found for select-odd/select-even)
> 
> * the select-button uses a label only
> 
> * that button opens a popover with two label-button: selOdd, selEven

I can't find _any_ icons for those actions at all, either good or bad, so we will go with the approach you summarized here, in the order [Select All -- ▲] [Cancel Selection].

**Comment by amivaleo** [comment]
> I didn't see that button before, thanks.

Np. And yes, the "back" button works the same.

> the learned lessons in the design department are difficult to translate

Sure. I know that. Slicer is somewhat closer to nautilus in these terms.

> in the order [Select All -- ▲] [Cancel Selection]

💪

Time to do the magic (code)! :)

**Comment by junrrein** [comment]
Implemented as of a770f65a2c5da3fa06aeb9eee60157a4326e269e.

**Comment by amivaleo** [comment]
I guess you still have to tell flatpak to release this version.

Anyway, don't forget to add **ctrl+A** shortcut to trigger the same "select all" action!

**Comment by junrrein** [comment]
Just FYI: The Ctrl+A shortcut was added back then, and a new release mas made, but I've hit a regression in the Flathub build machinery: https://github.com/flathub/flathub/issues/1078
