### ISSUE TITLE
Unusual saving location

### ISSUE THREAD

**Issue by Nokia808** [junrrein/pdfslicer#72]
Hi. I tried your application to manipulate PDF files. I noticed some strange behaviours ! 
One of these is unusual saving location of output file! 

Please see screenshot bellow:

![screenshot](https://user-images.githubusercontent.com/25375330/56719423-33672680-6730-11e9-85e0-b3f4f6e77ed3.png)
 
As you see, location to save output file is:
run/user/1000/doc/df0c07dc

Why this ? Isn't should be (by default, then user can change):
"home/myusername"
or
"home/myusername/Documents"

**Comment by junrrein** [comment]
Thanks for the report!

This is a bug I introduced while trying to implement #48, and I forgot to test if this worked under Flatpak. In retrospect, It's obvious it doesn't, but I should have tested this.
