### ISSUE TITLE
Size of output PDF is larger than that of input PDF after delete some pages

### ISSUE THREAD

**Issue by Nokia808** [junrrein/pdfslicer#74]
Hi. I noticed that after I deleted 3 pages (page 3, 4, & 5) from test.pdf, the size of output file "Untitled Document" was larger !!!

The input PDF "test.pdf" is 5.1 MG, while size of output PDF "Untitled Document" is 5.2 MB inspite the fact that process was a deletion process !!

I tried to perform following command line to use my system QPDF as following:
qpdf test.pdf test2.pdf
to see if there will be an increase in size due to optimization efforts that done by QPDF or not. The output of this command line operation was same of input file size (=5.1) inspite that process do not involve deletion of pages !!

Please see this case. I attach PDF files bellow:

[test.pdf](https://github.com/junrrein/pdfslicer/files/3115961/test.pdf)
[test2.pdf](https://github.com/junrrein/pdfslicer/files/3115962/test2.pdf)
[Untitled document.pdf](https://github.com/junrrein/pdfslicer/files/3115964/Untitled.document.pdf)

**Comment by junrrein** [comment]
Hi again, thanks for the report! :)

It seems that QPDF does nothing to the file when running `qpdf test.pdf test2.pdf`.

I replicated the same operation (deleting pages 3,4 and 5) using the command `qpdf --empty out.pdf --pages test.pdf 1-2,6-287 --`. The `out.pdf` file ends up weighing 5.2 MB, the same as when using Slicer.

Do you get a different result with that command?

I attach the result below:
[out.pdf](https://github.com/junrrein/pdfslicer/files/3117135/out.pdf)

**Comment by Nokia808** [comment]
@junrrein 
Just a moment ! As I know, (please correct to me if I'm wrong), the "--empty" to to do operation so that output PDF will be without metadata of original one. So, I do not understand what is role of "--empty" here - may be due to language barrier I misunderstand some thing !

**Comment by junrrein** [comment]
> Just a moment ! As I know, (please correct to me if I'm wrong), the "--empty" to to do operation so that output PDF will be without metadata of original one. So, I do not understand what is role of "--empty" here

The role of using the `--empty` option is to emulate what Slicer is doing when saving a document: It creates an empty PDF and then adds pages to it. I don't want Slicer to concern itself with metadata at all.

> How output PDF will be larger if it will be WITHOUT original metadata?

I don't know, ask the QPDF author.

By the way, do you get a different result than mine when running `qpdf --empty out.pdf --pages test.pdf 1-2,6-287 --`?

**Comment by Nokia808** [comment]
@junrrein 
I get 5.2 MB result from application of command you ask me to perform. But we have now new, & big, problem from using "empty" by default ! See:
https://github.com/junrrein/pdfslicer/issues/83

**Comment by junrrein** [comment]
So Slicer isn't doing anything wrong with regards to file size. I'm closing this issue.
