### ISSUE TITLE
Launching icon should be located within "Office" group not "Accessories"

### ISSUE THREAD

**Issue by Nokia808** [junrrein/pdfslicer#75]
I noticed that after installation of your application that it's launcher icons created within "Accessories" while it should be within "Office" group of my application menu !

Please to fix this.

I'm using Fedora 28 X64 Cinnamon edition.

**Comment by junrrein** [comment]
Thanks for the report!

Right now, the only category listed for Slicer is "Utility". I agree with you, it should also belong to the "Office" category.
