### ISSUE TITLE
Do you accept sponsored development to evolute pdfslices ?

### ISSUE THREAD

**Issue by Nokia808** [junrrein/pdfslicer#77]
Hi.
In short: I'm ready to donate you money to assist you to evolute your pdfslicer from just simple editor to advanced editor. 
I have only following conditions for that:

1) all new features remain open source & free for community,
2) pdfslicer remain open source & free for community,
3) road map of development will aim for include all powers of QPDF & OCRmyPDF backends
4) pdfslicer remain available on Flathub as flatpak so as to allow as much as possible of Linuxers to enjoy it.

If you accept for that, then inform me about how it cost you to cover time & resources that you will consume, so as to see how much I can cover from my side. 

From my side I can send you money by the following ways:

- by buying Bitcoin then send them to you,
- by pre-paid credit card. You should give me link of donation to use them to donate you on that link,
- by real money transfer by a real exchanger to send money to your exchanger receiver that you select & give me his address. I do not recommend this method

Please notice that PayPal is of no help because it is not available for those who reside inside Iraq like me.

**Comment by junrrein** [comment]
Hi @Nokia808.

Words will fall short for this, but let me tell you that I'm really flattered, moved and thankful for your proposal.

However, my current intentions towards Slicer is for it to stay being a hobby project. I'm a college student, and I'm currently also looking for a (traditional) part-time job. I simply cannot afford the time and commitment that your offer implies.

I see that you are from Iraq. It's nice seeing that people around the world find this little app useful :) Greetings from Argentina!
