### ISSUE TITLE
Ability to select all odd pages & select all even pages

### ISSUE THREAD

**Issue by Nokia808** [junrrein/pdfslicer#78]
Currently application allow user to select individual pages.

It will be very useful to add other 2 options: 

- select all odds pages
(like 1, 3, 5, 7, 9, ......)
- select all evens pages
(like 2, 4, 6, 8, 10, .......)

**Comment by junrrein** [comment]
I agree, this will be useful. These two functions will probably placed alongside #69.

**Comment by junrrein** [comment]
Could you tell me of situations where you wished you had these features? I know I said this would be useful, but right now I can't recall an use-case.

**Comment by Nokia808** [comment]
@junrrein 
When user need to add a stamp or a watermark or background or footer or header ........

For example: I like to add my name as a stamp over odd pages while add my email as stamp on even pages.

By the way, we are already open issue about add new feature "add stamp to selected page(s)"

**Comment by junrrein** [comment]
Thanks a lot for the examples!

**Comment by junrrein** [comment]
Implemented as of a770f65a2c5da3fa06aeb9eee60157a4326e269e.

**Comment by Nokia808** [comment]
@junrrein 
You are great in your work !
