### ISSUE TITLE
Improve UX when using the keyboard

### ISSUE THREAD

**Issue by amivaleo** [junrrein/pdfslicer#80]
Hi!

Try this:
- open any document in slicer
- [1] right after the document has been opened, it would be nice to be able to press 'space' to select the first page -> but the user has to press 'tab' a couple of times before the focus goes on the page grid
- [2] try to select several pages only using arrow-keys -> the user has to click the same  arrow-key twice in order to go select the next adjcent page

I hope the two issues are clear.

What do you think about them? Are they easy to fix? But before that, are they worthy those fixing (maybe only [2]...?)?

**Comment by junrrein** [comment]
Hi there, thanks for the report!

Actually I hadn't thought about selecting pages using only the keyboard. Improving this workflow would be nice.

I think both [1] and [2] are worth fixing.

**Comment by junrrein** [comment]
As of 002c7693abdc2252b5ab2acd71239a1d7c09f8fb, the following is implemented, and will be included in the next release:

* When a document is opened, the first page gets focused. It will seem like it doesn't, but it's just a visual bug with Gtk/Adwaita/whatever.
* You can navigate to other pages with only one keypress.
* You can select/deselect pages using the spacebar (this ability was lost some time ago).
* You can open the big preview of a focused page using Enter.

If you have other suggestions on this area just file those issues away! It may take me a long while to get to them (it took nearly one year for this one :smile:), but eventually they may end up getting done.
