### ISSUE TITLE
[Feature request] Extract pages (range of pages) to single output PDF

### ISSUE THREAD

**Issue by Nokia808** [junrrein/pdfslicer#82]
This functionality is well supported by QPDF backend. I failed to see such option in current version of pdfslicer in-spite the fact that it is documented on home page of GitHub site of pdfslicer that pdfslicer support extraction of PDF pages

**Comment by junrrein** [comment]
Can you clarify how you expect this to work?

If you want to save a range of pages to a PDF, I expect the user to remove all the others (using the `Remove unselected` option) and then saving the result.

**Comment by Nokia808** [comment]
@junrrein 
Dear your approach based on INDIRECT solving of problem which is highly inconvenient !  It is very unusual !

I need at multiple occasions to extract from a book, for example composed from 24 chapters, I need to extract 4 chapters, each to single PDF file.

**Comment by junrrein** [comment]
> Dear your approach based on INDIRECT solving of problem based on already available features & avoiding adding new options ! This is highly inconvenient ! It is very unusual !

The philosophy of Slicer is "everything you see on the screen is what's going to get saved". Any feature that does not fit in this model is not going to get in, including the one brought up by this issue.

> According to your approach, I have to undo my actions many times which is something inconvenient !

Currently you have to hit the undo button once for each chapter, yes.

> This will not allow your application to be popular ......

Being popular isn't in the list of the reasons why I started this project. And in the future, please abstain from making value judgements that aren't relevant to the issue at hand.
