### ISSUE TITLE
Copy metadata from the original file

### ISSUE THREAD

**Issue by Nokia808** [junrrein/pdfslicer#83]
Hi. Dear there is a great problem in your use of "--empty" as a default option for operations of QPDF in your application: it is the loss of outlines (bookmarks) of PDF which reffer to various chapters & sections of e-book ! 

Outlines is very valuable thing in e-book ! Do you will buy an scientific or historical book without index page ?

I suggest on you not to use "--empty" by default in QPDF within your application. You can add "General setting" for your application & make it has an option to enable/disable "--empty" ....... This is the best solution. No one like to loss outlines of heir/his e-books ......

**Comment by junrrein** [comment]
I agree that metadata should be carried over the new file. There will be a couple of issues though:

* QPDF doesn't provide a way to combine metadata (or at least the outline) of two documents. So the best that can be done here is to carry over the metadata of the first file.
* I don't know if I'll be able to implement this even when modifying a single file. The ability to move pages around can only be implemented using QPDF by removing pages and inserting them somewhere else, and I'm afraid this can get rid of the anchor points used by the outline. Regardless, it's worth a try.

**Comment by Nokia808** [comment]
@junrrein 
Dear, I think that the best way is to make direct contact between you & QPDF developer. You can explain to him directly on GitHub & he will never ever disappoint you.

**Comment by junrrein** [comment]
As of 0a10da942990753df961b309d164559b12baf130, Slicer now copies the metadata and outline of the first opened file when saving a document.

**Comment by junrrein** [comment]
A suggestion: maybe the bug report you opened in the QPDF Github about this issue can now be closed :)

**Comment by junrrein** [comment]
Currently, I have no straightforward way to merge the outlines of every merged document, since that's not supported by QPDF. I'm tracking that at #156.
