### ISSUE TITLE
Selected pages should have a distinguishing background

### ISSUE THREAD

**Issue by junrrein** [junrrein/pdfslicer#84]
From https://github.com/junrrein/pdfslicer/issues/30#issuecomment-489116521:

> the page-grid should be very similar to that used by nautilus, or gnome-boxed (in grid mode), or gnome-games-app, or gnome-music, etc. Meaning: the selected page should have a blue background just like a selected file in nautilus.

**Comment by junrrein** [comment]
@amivaleo 

I completely agree with this. I just have to do the research about how to implement it.

**Comment by junrrein** [comment]
@amivaleo 

It turned out doing this was really easy. This is how it looks right now:

![Captura de pantalla de 2019-05-07 23-47-23](https://user-images.githubusercontent.com/962049/57345777-8672ad80-7122-11e9-883b-b4e769eb36bb.png)

Without check marks:

![Captura de pantalla de 2019-05-07 23-46-44](https://user-images.githubusercontent.com/962049/57345775-84a8ea00-7122-11e9-93ab-e05347602ff7.png)

Do you think the check marks should stay or go?

**Comment by amivaleo** [comment]
I think the checkboxes are redundant, and also quite hard to spot since they're tiny. I'd go for the second idea: only blue background.
