### ISSUE TITLE
Replace the zoom buttons with a slider in the hamburguer menu

### ISSUE THREAD

**Issue by junrrein** [junrrein/pdfslicer#87]
From https://github.com/junrrein/pdfslicer/issues/30#issuecomment-489116521:

> remove the couplet of zoom button -/+ and put a slider in the hamburger menu for zooming.

**Comment by junrrein** [comment]
@amivaleo I agree with this wholeheartedly, nice suggestion!

**Comment by amivaleo** [comment]
I'm glad that you appreciate! :)

I tried to suggest the same idea for nautilus, but never got a reply. 😞

**Comment by junrrein** [comment]
Current implementation:

![Captura de pantalla de 2019-05-18 19-09-34](https://user-images.githubusercontent.com/962049/57975510-969b5000-79a0-11e9-94da-1af083e77ce6.png)

I think it's kind of non-descript. Maybe we could show some indicator of what the slider is for? Dunno.

**Comment by amivaleo** [comment]
> it's kind of non-descript

Yep. My suggestion is to follow what GSConnect extension does in its hamburger menu: https://github.com/andyholmes/gnome-shell-extension-gsconnect/pull/368#issuecomment-445645987

You could use the label "zoom" and voilà. 🤔

**Comment by junrrein** [comment]
@amivaleo 

I agree, a label above the slider should be enough.

**Comment by junrrein** [comment]
I got a strange visual issue when adding the "Zoom" header to the menu, but I've filed it as bug #95.

Meanwhile, I consider this feature as implemented.
