### ISSUE TITLE
Misc changes to button layout

### ISSUE THREAD

**Issue by junrrein** [junrrein/pdfslicer#89]
From https://github.com/junrrein/pdfslicer/issues/30#issuecomment-489116521:

> * transform the icon-based "open" button into a text-based.
> * move the save-button to the right and make it text-based. I think i'ts not good to have "open" and "save" both icon-based and both close to each other. In particular, from the "phylosophical" point of view, "open" is somewhat related to idea of "creating" and "starting". "save" is close to the idea of "closing"/"storing"/"close everything, we need to leave!".

**Comment by junrrein** [comment]
@amivaleo 

I agree with this suggestion. This kind of layout would match the one in Gedit, so being consistent with other apps is also nice.

**Comment by amivaleo** [comment]
Indeed, I was thinking about gedit (and glade, evince -whose save-feature is in the hambuger menu, but still on the right-, gtranslator, etc) when I suggested these changes.

I don't remember similar suggestion in the HIGs, nevertheless I believe that it is good to follow some common layout for similar features. Like: I would be quite weird to have one single app showing the "open" button on the left of the headerbar, for example. You can do that, it's only quite annoying for the user, I think.

**Comment by amivaleo** [comment]
How can I help you in speeding up the coding of these changes? :(

I read your replies about "how to learn coding applications". It's a long road, indeed...

**Comment by amivaleo** [comment]
Yep. Still, the road drawn in #68 can't lead me to give some help with coding in a short time.

I'm sorry for that.

**Comment by amivaleo** [comment]
Yep. Still, it's a long road the one drawn in #68 and I'll not be able to give some help with coding in a short time... :\

I'm sorry for that.

**Comment by junrrein** [comment]
> Yep. Still, the road drawn in #68 can't lead me to give some help with coding in a short time.
>
> I'm sorry for that.

It's indeed not a short road, so don't be sorry about it! There's so much to do in life, and so little time :)

**Comment by junrrein** [comment]
@amivaleo 

Current state (ignore page labels and app title):

![Captura de pantalla de 2019-05-08 19-47-26](https://user-images.githubusercontent.com/962049/57413376-4a932300-71ca-11e9-83d3-4af0ac4a6527.png)

What do you think about the button labels?

**Comment by amivaleo** [comment]
> What do you think about the button labels?
*Almost* perfect! :)

It's "Save As..." with capital A.
I think that the S in "Cancel selection" should be capitalized too. I'm not very good with this, since my native language doesn't follow such rule.

Why the hamburger menu now has a 3-dots icon? o.O
The 3-lines icon should be used on the main page of the application, while the 3-dots icon is to be used for a "secondary menu" (or: on secondary pages). I can't find this statement on the HIGs, but here, from Allan Day: https://gitlab.gnome.org/GNOME/Initiatives/wikis/App-Menu-Retirement

What about switching the positions of the rotation-buttons and the move-buttons in the bottom bar? Something tells me that "moving" should go before "rotating". 🤔

**Comment by junrrein** [comment]
@amivaleo 

> It's "Save As..." with capital A.
> I think that the S in "Cancel selection" should be capitalized too. I'm not very good with this, since my native language doesn't follow such rule.

Done and done. I didn't know the [Gnome HIG recommended header capitalization for text buttons](https://developer.gnome.org/hig/stable/buttons.html.en), thanks for the info.

> Why the hamburger menu now has a 3-dots icon? o.O

That was just a custom icon theme, sorry to confuse you.

> What about switching the positions of the rotation-buttons and the move-buttons in the bottom bar? Something tells me that "moving" should go before "rotating". :thinking:

I don't have a strong opinion on this, so done. Move-buttons came after rotation-buttons just because I implemented them later.

With the new changes (and the Adwaita icon theme):

![Captura de pantalla de 2019-05-09 11-21-21](https://user-images.githubusercontent.com/962049/57461346-380dfd80-724d-11e9-8d52-275f9a7cb3af.png)

**Comment by amivaleo** [comment]
Only one concern left:

The string "Page" in the page labels. 🤔

I only wonder if that can be removed or not. Just wondering. The only reason is: by removing it, some space can be saved.

Nice result, Julian. :)


As you might have understood, I tend to be a perfectionist. So... Why the up-arrow butotn to the right of the trash bin icon is not compact as in nautilus?

![Schermata da 2019-05-09 16-34-43](https://user-images.githubusercontent.com/24316547/57462019-605f2180-7278-11e9-9650-52f0f47aded1.png)

**Comment by junrrein** [comment]
> The string "Page" in the page labels. :thinking:
>
> I only wonder if that can be removed or not. Just wondering. The only reason is: by removing it, some space can be saved.

Keep in mind these labels was an in-progress change that I shouldn't have committed to master. In the next release, page labels will look as we've talked about in #88

> As you might have understood, I tend to be a perfectionist. So... Why the up-arrow button to the right of the trash bin icon is not compact as in nautilus?
> ![](https://user-images.githubusercontent.com/24316547/57462019-605f2180-7278-11e9-9650-52f0f47aded1.png)

I just didn't notice the Nautilus button was compact like that. I like it indeed. I'll do that next.

**Comment by junrrein** [comment]
@amivaleo 

With the thinner button:

![Captura de pantalla de 2019-05-09 12-52-48](https://user-images.githubusercontent.com/962049/57467787-8de8a280-7259-11e9-96cb-ffb77e10856d.png)

Any other suggestions in this area?

**Comment by amivaleo** [comment]
Nope.

I think you're done here. It can't be any better, I think. ;)

**Comment by junrrein** [comment]
This is all done as of cdeabd65611dc3d760ad2b0474d4f0effb6033c5.
