### ISSUE TITLE
Added pages should get selected by default

### ISSUE THREAD

**Issue by junrrein** [junrrein/pdfslicer#93]
From https://github.com/junrrein/pdfslicer/issues/88#issuecomment-492534980:

> I would like to suggest to make the newly added pages selected right after being added, so that the user can easily drag/move them inside the document.

**Comment by junrrein** [comment]
This is already implemented in master.

**Comment by amivaleo** [comment]
Although new pages are indeed selected by default, the "Cancel Selection" button is inactive after the new pages are added.

**Comment by junrrein** [comment]
@amivaleo 

Thanks for bringing that up! Fixed in 701ea5a5ab5ca68fcbf836a2d83ab1fdb1aa0cb0.
