### ISSUE TITLE
Zoom header in AppMenu shows wide separators

### ISSUE THREAD

**Issue by junrrein** [junrrein/pdfslicer#95]
Currently, it looks like this:

![Captura de pantalla de 2019-06-17 19-05-26](https://user-images.githubusercontent.com/962049/59639956-06812f80-9133-11e9-850e-f20e9c72475c.png)

The separators shown alongside the Zoom header should be narrow like the separator below it.

**Comment by amivaleo** [comment]
Hi!

I don't know if there's a "correct" way of doing this, but this is what I tried for another project and it works:
[popover.zip](https://github.com/junrrein/pdfslicer/files/3301333/popover.zip)

You can try and use that if it helps. :)

**Comment by junrrein** [comment]
@amivaleo 

The Glade example you gave actually helped find where the problem was. It was an issue with vertical alignment of the separators. Thanks a lot!
