### ISSUE TITLE
UI: Zoom slider works randomly

### ISSUE THREAD

**Issue by amivaleo** [junrrein/pdfslicer#98]
Hi!

Try to play a bit with the zoom slider in the hamburger menu. It works in some random way.

Also try to scroll the mouse wheel while hovering that. It's... Weird.

(A bit OT: I suggest to add two flat circular buttons, one at each end of that slider, showing a + and a - for respectively increasing and decreasing the zoom. If you agree on this, let's open a new issue.)

**Comment by junrrein** [comment]
Hey there!

I can't reproduce these issues. Can you upload a video or gif showing these problems?

**Comment by amivaleo** [comment]
Sure!

A video for you: https://drive.google.com/file/d/13JugMRV51TuND6aSntz5L0h86wX1OQuJ/view

**Comment by junrrein** [comment]
LOL that is absolutely bizarre. And I can't reproduce that, as much as I try.

I'm pushing version 1.7.1 to Flathub, and it should be available within the next 24 hours. I didn't change anything related to the zoom slider, but you could try and report back.

Failing that, I'll ask if you can reproduce this reliably, and a list of steps to trigger this.

Thanks for the video!

**Comment by amivaleo** [comment]
> LOL that is absolutely bizarre
Yes. :)
That's why I couldn't find better words to explain this issue.

As far as I can get it, it looks like that there are more zooming steps than those allowed by the sliders (which should only allow 3). 🤔

There's nothing specific I do: I open a pdf in slicer > open the hamburger-menu > try to change the zooming level using the mouse wheel. But even if I drag the cursor...! Look: https://drive.google.com/file/d/1CKPgQ_9eJN1UG33FzXA8fFZ3oInx3650/view?usp=sharing

**Comment by amivaleo** [comment]
I've just updated to the latest release. I noticed that the slider cursor correctly updates if the mouse cursor leaves the hovering area:

1. open the hamburger menu after loading any pdf
2. hover the zoom slider with the mouse cursor and make *one* single step with the mouse wheel => the zoom level changes but the slider is not updated
3. move the mouse cursor away from the slider => the slider correctly updates

This gif shows such procedure: https://im.ezgif.com/tmp/ezgif-1-11e7d4ceefad.gif

**Comment by junrrein** [comment]
I think I cracked the puzzle: I can reproduce this on Wayland, but not on X11. Can you confirm this?

**Comment by amivaleo** [comment]
You're right, sir! The slider works fine on xorg.

Why do you use wayland, by the way? D:

**Comment by junrrein** [comment]
> You're right, sir! The slider works fine on xorg.

This all means that the bug probably lies within Gtk or Mutter, I dunno. I'll drop by the Gnome IRC channel and see where I should file this.

> Why do you use xorg, by the way? D:

I don't remember right now, but I probably had a couple of small isues with Wayland. Every year or so I give it an honest try, so next time we'll see.

**Comment by junrrein** [comment]
[Gtk bug report](https://gitlab.gnome.org/GNOME/gtk/issues/1970).
