### ISSUE TITLE
UI: add label and item in the "add pages" popover

### ISSUE THREAD

**Issue by amivaleo** [junrrein/pdfslicer#99]
Hi!

I'd like to suggest two changes to the popover menu for adding new pdf (the one that is linked to the + button), so that it would look like this:

Add a Blank Page
--- Add a Document ---
At the Beginning...
At the End...
After the Selected Page...

And the hint on the + button could be "Add a Document or a Blank Page".

This change makes sense after the "add blank page" https://github.com/junrrein/pdfslicer/issues/66 feature is available of course.

Nevertheless, I still suggest to add the label "--- Add a Document ---" in that popover, just to make it even clearer what those "at the beginning/end" mean.

**Comment by junrrein** [comment]
Hey there!

I agree about adding an "--- Add a Document ---" header to the menu.

Is the tooltip on the "+" button really necessary after that? I think the button by itself is pretty self-explanatory.

**Comment by amivaleo** [comment]
> Is the tooltip on the "+" button really necessary after that? I think the button by itself is pretty self-explanatory.

My personal thought is that every single button, in every pieace of gui, should have tooltips. Even if they are completely self-explanatory.

But that's my opinion. :)

This is one of the things that should be asked to the the "gnome-guys" (i.e.: Allan Day).

**Comment by junrrein** [comment]
I don't have a strong preference on the matter, so having the tooltip stay doesn't irk me :+1:

**Comment by amivaleo** [comment]
If I try to find some rationale reason, I guees that as a general rule the text-buttons need tooltips less than image-only-button. 🤔

Keep it for now. I'll get back to this point when I get some "official" reply on this.

**Comment by junrrein** [comment]
Honestly, the rationale you provided (icon buttons need tooltips while text buttons don't) is good enough for me. Don't bother yourself about getting an "official" opinion just for Slicer. Thanks!
